version: '3.7'
services:
  db:
    image: mysql:latest
    container_name: mysql_1
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'mysql_password'
      MYSQL_DATABASE: 'BANK'