spring:
    config:
        activate:
            on-profile: prod
    application:
        name: ${SPRING_APP_NAME:securitybasics}
    devtools:
        add-properties: false
    datasource:
        url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/BANK}
        username: ${SPRING_DATASOURCE_USERNAME:root}
        password: ${SPRING_DATASOURCE_PASSWORD:mysql_password}

    jpa:
      show-sql: false
      properties:
        hibernate:
          format_sql: false

  #security:
    #    user:
    #        name: ${SECURITY_USERNAME:santy}
    #        password: ${SECURITY_PASSWORD:12345}

logging:
  level:
    org.springframework.security: ERROR