name: Java CI with Maven

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Determine section from branch name
      run: |
        section=$(echo "${GITHUB_HEAD_REF}" | cut -d '/' -f 1) 
        echo "SECTION=$section" >> $GITHUB_ENV

    - name: Print section
      run: |
        echo "Section: $SECTION"

    - name: Build with Maven
      run: mvn -B package --file $SECTION/pom.xml

  docker_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Determine section from branch name
      run: |
        section=$(echo "${GITHUB_HEAD_REF}" | cut -d '/' -f 1) 
        echo "SECTION=$section" >> $GITHUB_ENV
    
    - name: Print section
      run: |
        echo "Section: $SECTION"

    - name: Build Docker Image
      run: |
        cd $SECTION
        pwd
        docker build -t ${{ vars.DOCKER_REPO }}/$SECTION:$GITHUB_SHA -t ${{ vars.DOCKER_REPO }}/$SECTION:latest -f $SECTION/docker/Dockerfile .

    - name: Push Docker Image
      run: |
        docker push ${{ vars.DOCKER_REPO }}/$SECTION:$GITHUB_SHA
        docker push ${{ vars.DOCKER_REPO }}/$SECTION:latest

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    #- name: Update dependency graph
    #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6